### ISSUE TITLE
코드의 가독성을 높이기 위한 예외 처리 어노테이션

### ISSUE THREAD

**Issue by yu-teacher** [dodeca05/wolMgr#14]
# 무엇이 문제인가요? (What)
try catch문과 throws를 사용해야 하는 상황이 있을 수 있습니다. 
하지만 try catch문은 코드의 가독성을 해칠 수 있습니다. 

# 어떻게 해결하고 구현했나요? (How)
따라서 별도의 예외처리를 구현해야 할 상황( 예외가 발생하면 특정 로직을 수행해야 한다. )이 아니라면 
Lombok의 `@SneakyThrows`을 사용하면 어떨까 제안합니다.

사용예시는 이렇습니다.

```
import lombok.SneakyThrows;

public class Example {
    @SneakyThrows
    public void doSomething() {
        // 예외를 발생시킬 수 있는 코드
    }
}
```

이 어노테이션은 생성자와 메서드에 사용할 수 있습니다.

하지만 이 어노테이션은 예외를 무시하고 넘어가기 때문에 예외를 처리하는 별도 로직이 필요한 상황에서는 적합하지 않습니다.
따라서 별도의 예외처리가 필요하지 않은 상황이라면 이것을 사용하면 어떨까 제안합니다.

# 테스트 했나요?
- [x] Local Test (본인 pc 에서 테스트)
- [ ] include Test Code (테스트 코드 포함)

**Comment by dodeca05** [comment]
로그가 남지 않는다는 부분이 매우 치명적 입니다. 사용하지 않는 것이 좋겠습니다

**Comment by yu-teacher** [comment]
넵
