### ISSUE TITLE
smtp 개발 환경 사용시 비활성화 여부

### ISSUE THREAD

**Issue by dodeca05** [dodeca05/wolMgr#15]
구글 계정에서 smtp를 사용하는 설정이 따로 있는 것으로 알고 있습니다만 
              해당 설정에서 MAC 주소 등 개인정보를 요구 할 것 입니다.
각자 SMTP를 설정 할 수 는 있지만 이는 다소 번거롭고 모든 개발자가 다루는 영역이 아니기 때문에 smtp가 환경 변수로 등록되어 있지 않으면 smtp기능이 비활성화 되는 코드를 넣는 건 어떨까요?

해당 코드가 잘 못 되었다는건 아니고 저의 제안 입니다.

_Originally posted by @dodeca05 in https://github.com/dodeca05/wolMgr/pull/11#discussion_r1164720316_

**Comment by yu-teacher** [comment]
말씀이 이해가 잘 가지 않는데 

```
    @Bean // Spring Bean으로 등록됨을 표시
    public JavaMailSender getJavaMailSender() { // JavaMailSender 객체를 생성하는 메소드
        JavaMailSenderImpl mailSender = new JavaMailSenderImpl(); // JavaMailSenderImpl 객체 생성

        mailSender.setHost("smtp.gmail.com"); // 메일 서버 호스트 설정
        mailSender.setPort(587); // 메일 서버 포트 설정

        mailSender.setUsername(env.getProperty("auth_email")); // 인증에 사용할 이메일 계정 설정
        mailSender.setPassword(env.getProperty("auth_password")); // 인증에 사용할 이메일 계정의 비밀번호 설정

        Properties props = mailSender.getJavaMailProperties(); // JavaMail의 속성(Properties) 설정 객체 얻기
        props.put("mail.transport.protocol", "smtp"); // 메일 전송 프로토콜 설정
        props.put("mail.smtp.auth", "true"); // SMTP 인증 사용 설정
        props.put("mail.smtp.starttls.enable", "true"); // STARTTLS 사용 설정
        props.put("mail.smtp.ssl.trust", "smtp.gmail.com"); // Gmail 서버 신뢰 설정
        props.put("mail.smtp.ssl.protocols", "TLSv1.2"); // SSL 프로토콜 설정

        return mailSender; // 생성된 JavaMailSender 객체 반환
    }
```

이 코드의

```
        Properties props = mailSender.getJavaMailProperties(); // JavaMail의 속성(Properties) 설정 객체 얻기
        props.put("mail.transport.protocol", "smtp"); // 메일 전송 프로토콜 설정
        props.put("mail.smtp.auth", "true"); // SMTP 인증 사용 설정
        props.put("mail.smtp.starttls.enable", "true"); // STARTTLS 사용 설정
        props.put("mail.smtp.ssl.trust", "smtp.gmail.com"); // Gmail 서버 신뢰 설정
        props.put("mail.smtp.ssl.protocols", "TLSv1.2"); // SSL 프로토콜 설정
```

이 부분이 SMTP 설정입니다. 부가 설명 가능한가요?

**Comment by dodeca05** [comment]
환경변수를 가져오는 부분을 try catch 로 감싸서 환경변수가 없을 때 smtp 기능이 비활성화 되도록 했으면 좋겠습니다
현재는 가져오는 환경변수가 없으면 실행이 안될 것으로 보입니다.

이런 설정을 하는 주장은 다음과 같습니다.

- **메일 기능은 중요하지 않습니다**

     - 현재 코드는 회원가입시 메일 보내는 기능을 사용하고 있고 다른 기능에는 사용하지 않고 있습니다.
     - DB는 해당 서버에서 전체적으로 반드시 중요한 역할을 담당하고 있습니다. 따라서 DB 설정이 문제가 있으면 반드시 에러를 띄우고 서버를 멈춰야 합니다. 그러나 메일은 아닙니다. 회원가입은 DB SQL로 할 수 있고 내부 intra를 구성하는 프로젝트라 메일 회원가입에 대한 필요성이 더욱더 떨어집니다.

- **메일 기능이 전체 로직에 영향을 끼치지 않습니다**
     - 앞에 말한 이유와 상당히 겹치는 부분입니다만 메일이 회원가입 외 중요하지 않습니다. 그 뜻은 해당 코드를 유지 보수 하는 일이 생길 경우 메일 설정이 중요한 경우는 거의 없다는 것 입니다. 그러나 지금과 같은 구성을 가진다면 새로운 개발자가 투입 될 경우 최초 설정에 번거로움만 늘어나게 됩니다.

- **Google smtp 는 MAC 주소를 요구합니다**
     - (이부분은 오피셜이 아닐 수 있습니다)
     - 보안 설정때문에 Google smtp서버를 사용할 경우 mac 주소 제한을 두는 것으로 알고 있습니다. 그러게 되면 하나의 계정을 공유하는게 불가능하고 개발자 각자 고유의 smtp계정이 하나씩 있어야 됩니다. 

- **추후 프로젝트와 겹칩니다**
     - 메일 기능은 msa형태로 alertMgr에 기획될 예정입니다.
     - alertMgr에 이를 넣은 이유는 Google smtp서버가 mac주소를 요구하는 것으로 알고 있는데 현재 실행되는 물리 서버가 여러대 이므로 메일을 보내는 서버는 하나로 하고 다른 서버나 애플리케이션이 메일 담당 서버에 요청을 보내는 식으로 프로젝트를 기획하고 있습니다.

하지만 메일 기능을 제거하는 것은 반대입니다.
추후 메일 기능이 다른 부분에 필요할지 아직 모르기 때문입니다.
따라서 해당 기능이 필요한 사람만 활성화 되도록 환경변수에 메일 관련 설정이 있을 때만 smtp 서비스가 살아나도록 설계하고 싶습니다.

참고 : 잘 알려진 이론이 아니라 의견입니다.

**Comment by yu-teacher** [comment]
기능 비활성화를 말씀하시는 것이 회원가입 이메일 인증 기능을 비활성화 하자는 말씀인가요?

**Comment by dodeca05** [comment]
> 기능 비활성화를 말씀하시는 것이 회원가입 이메일 인증 기능을 비활성화 하자는 말씀인가요?

넵

**Comment by yu-teacher** [comment]
메일인증기능을 사용한 것은 유효한 사용자인지 판별함이 목적입니다. 따라서 메일은 alertmgr로 옮기고 메일인증 기능을 삭제하면 어떨까요? 로컬서비스이기 때문에 유효사용자인지 판별하는 기능은 필요 없을 듯 합니다

**Comment by dodeca05** [comment]
이미 개발된 기능이고 AlertMgr이 문제가 생기는 경우나 다른 환경에서 이 애플리케이션을 실행시 최대한 의존성을 줄이는 측면을 고려하면 안지우는게 좋다고 생각합니다

**Comment by yu-teacher** [comment]
그렇다면 코드는 유지한 채 환경변수에서 Null값을 받아온다면 비활성화 되는 로직을 짜는게 최선이겠군요? 
프론트의 인증메일관련 프론트 html, js 또한 비활성화 되야 할 필요가 있겠네요 그렇게 수정할까요?

**Comment by dodeca05** [comment]
담당자 주관에 맏기겠습니다

**Comment by yu-teacher** [comment]
> 그렇다면 코드는 유지한 채 환경변수에서 Null값을 받아온다면 비활성화 되는 로직을 짜는게 최선이겠군요? 프론트의 인증메일관련 프론트 html, js 또한 비활성화 되야 할 필요가 있겠네요 그렇게 수정할까요?

이렇게 수정 완료 하였습니다.
